disabled_rules:
  - identifier_name
  - type_name
excluded:
  - WoosmapGeofencing/Sources/WoosmapGeofencing/Logging/OSLog.swift
type_name:
  excluded: T
nesting:
  type_level: 3
file_length:
  warning: 1000
  error: 1500
function_body_length:
  warning: 75
  error: 100
cyclomatic_complexity:
  ignores_case_statements: true

# Remove these lines once you have fixed/clean your codebase
force_cast:
  severity: warning
force_try:
  severity: warning
line_length: 500