name: "WoosmapGeofencing"

on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  iOS:
    name: Test iOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.5.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
